default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 7 } %>

development:
  primary: &primary_development
    <<: *default
    database: wit_calendar_backend_development
  queue:
    <<: *primary_development
    database: wit_calendar_backend_development_queue
    migrations_paths: db/queue_migrate

test:
    primary: &primary_test
        <<: *default
        database: wit_calendar_backend_test<%= ENV['TEST_ENV_NUMBER'] %>
        username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
        password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>
        host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
        port: <%= ENV.fetch("DB_PORT") { 5432 } %>
    queue:
        <<: *primary_test
        database: wit_calendar_backend_test_queue<%= ENV['TEST_ENV_NUMBER'] %>
        migrations_paths: db/queue_migrate

staging:
  primary: &primary_staging
    <<: *default
    database: wit_calendar_backend_staging
    username: wit_calendar_backend
    password: <%= ENV["WIT_CALENDAR_BACKEND_DATABASE_PASSWORD"] %>
  queue:
    <<: *primary_staging
    database: wit_calendar_backend_staging_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 7 } %>
    host: <%= ENV.fetch("DB_HOST") { "wit_calendar_backend-db" } %>
    port: <%= ENV.fetch("DB_PORT") { 5432 } %>
    database: <%= ENV.fetch("DB_NAME") { "wit_calendar_backend_production" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "wit_calendar_backend" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  queue:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 7 } %>
    host: <%= ENV.fetch("DB_HOST") { "wit_calendar_backend-db" } %>
    port: <%= ENV.fetch("DB_PORT") { 5432 } %>
    database: <%= ENV.fetch("DB_NAME_QUEUE") { "wit_calendar_backend_production_queue" } %>
    username: <%= ENV.fetch("DB_USERNAME") { "wit_calendar_backend" } %>
    password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
    migrations_paths: db/queue_migrate